name: Builder Noetic

on:
  workflow_dispatch:
  push:
    paths:
      - ros1.repos
jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: qiayuanl/ros-deb-builder-action@main
        with:
          DEB_DISTRO: focal
          ROS_DISTRO: noetic
          REPOS_FILE: ros1.repos
          SQUASH_HISTORY: true
          SKIP_PACKAGES: >-
            rm_referee
